name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  setup:
    name: Setup Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch master to compare coverage
      run: git fetch --depth=1 origin master

    - name: Run Setup
      run: echo "In Setup"

  test:
    name: Setup Tests
    runs-on: ubuntu-latest

    steps:
      - name: Run Tests
        run: echo "In Test"

  Ne:
    name: Setup Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Setup
        run: echo "In Setup"