name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  run_tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch master to compare coverage
      run: git fetch --depth=1 origin master

    - name: Install Required System Packages
      run: git branch -a

