name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  Test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.8, 3.9]

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Tests
        continue-on-error: true
        run: |
          mkdir reports
          cd reports
          python --version >> report.log
          python --version && sleep $(shuf -i 60-120 -n 1)

      - name: Save Job Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Build-Artifacts
          path: |
            **/reports/**/*
            test_root/log/**/*.log
            *.log